#!/bin/bash

# TaskFlow Email Setup Helper Script

echo "🚀 TaskFlow Email Configuration Setup"
echo "========================================"
echo ""
echo "⚠️  Gmail requires an App Password for sending emails"
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1️⃣  Enable 2-Factor Authentication:"
echo "    👉 https://myaccount.google.com/security"
echo "    • Click '2-Step Verification'"
echo "    • Complete the setup process"
echo ""
echo "2️⃣  Generate App Password:"
echo "    👉 https://myaccount.google.com/apppasswords"
echo "    • Select App: Mail"
echo "    • Select Device: Windows Computer (or your OS)"
echo "    • Click 'Generate'"
echo "    • 📋 Copy the 16-character password (looks like: xxxx xxxx xxxx xxxx)"
echo ""
echo "3️⃣  Update .env file:"
echo "    EMAIL_USER=your-email@gmail.com"
echo "    EMAIL_PASS=xxxx xxxx xxxx xxxx   ← Paste the 16-char password here"
echo ""
echo "4️⃣  Restart the server:"
echo "    npm start"
echo ""
echo "✅ Done! Emails will now send successfully"
echo ""
read -p "Press Enter once you've updated the .env file and restarted the server..."
